### ISSUE TITLE
Cannot use this pod w/ a Swift project w/ Swift dependencies

### ISSUE THREAD

**Issue by aaronwhite** [segment-integrations/analytics-ios-integration-optimizely#2]
My project depends on alamofire and other swift-native pods, including
`pod 'Segment-Optimizely', '~>1.0.0'` results in `The 'Pods' target has transitive dependencies that include static binaries: (Pods/Optimizely-iOS-SDK/Optimizely.framework)`

**Comment by f2prateek** [comment]
Is there anything we can do? This is likely something to bring up with Oprimizely since they only offer their library as a static binary IIRC.

**Comment by aaronwhite** [comment]
@f2prateek Unfortunately, I'm not pod-fluent enough to say, but logging it here if others can/want to chime in. I do know can include the Optimizely pod directly and it works fine, so I can't say if the ball is in their court, cocoa pods court, this court, Apple's court etc :/

**Comment by f2prateek** [comment]
@aaronwhite How were you using the Optimizely dependency directly in your project? Could you share your Podfile?

**Comment by aaronwhite** [comment]
@f2prateek 

```
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

#Analytics
  #Segment.com
  pod 'Analytics',          '~> 3.0.6'
  pod 'Optimizely-iOS-SDK', '~> 1.3.2'
```

**Comment by hankim813** [comment]
@f2prateek anything we can do here?

**Comment by f2prateek** [comment]
Same as https://github.com/segment-integrations/analytics-ios-integration-google-analytics/issues/3#issuecomment-203115637
