### ISSUE TITLE
'Segment-Optimizely' pod depends on old version of `Analytics` pod

### ISSUE THREAD

**Issue by trick14** [segment-integrations/analytics-ios-integration-optimizely#8]
In our project, I'm using `Segment-Amplitude` and recently I'm trying to add `Segment-Optimizely`. But they depend on different versions of `Analytics`. So I can't get `pod install` to succeed.

_Podfile_

``` Ruby
pod 'Segment-Amplitude', '~> 1.4.1'
pod 'Segment-Optimizely', '~> 1.1.0'
```

_error log_

``` Ruby
[!] Unable to satisfy the following requirements:

- `Analytics (~> 3.5.0)` required by `Podfile`
- `Analytics (= 3.5.2)` required by `Podfile.lock`
- `Analytics (~> 3.2)` required by `Segment-Amplitude (1.4.1)`
- `Analytics (~> 3.0.3)` required by `Segment-Optimizely (1.1.0)`
```

Can you update `Segment-Optimizely` pod?

**Comment by f2prateek** [comment]
This is fixed on [`master`](https://github.com/segment-integrations/analytics-ios-integration-optimizely/commit/fd8b10952bf014e148890b995d98b0ebf9a1008d) but not yet released. We'll have it out this week, but you could use `master` in the meantime.

```
pod 'Segment-Optimizely', :git => 'https://github.com/segment-integrations/analytics-ios-integration-optimizely.git'
```

**Comment by trick14** [comment]
@f2prateek If I run `pod install` with the podspec, I got this error.

```
[!] The 'Pods-Surfline' target has transitive dependencies that include static binaries:
(/Users/rhan/Documents/ios/surfline-ios/Pods/Optimizely-iOS-SDK/Optimizely.framework)
```

Even I tried without `Segment-Amplitude`, I got this too.

**Comment by f2prateek** [comment]
If you have `use_frameworks` in your Podfile, CocoaPods disallows static libraries as transitive dependencies. See https://github.com/CocoaPods/CocoaPods/issues/2926 and https://github.com/CocoaPods/CocoaPods/issues/3194#issuecomment-151767972.

i.e. for a chain App depends on `pod Foo` which depends on `pod Bar`, if Bar is a static library, CocoaPods will refuse to build it.

This outside the scope of Segment to fix currently, and the only solution is to ask Optimizely to distribute their library as a dynamic framework https://github.com/CocoaPods/CocoaPods/issues/5624#issuecomment-232634301.

There are a few workarounds, I think the best one is to copy these files https://github.com/segment-integrations/analytics-ios-integration-optimizely/tree/master/Pod/Classes into your source tree and add a dependency on Optimizely `s.dependency 'Optimizely-iOS-SDK', '~> 1.4.2'`.

While it's not ideal as the other integrations which are distributed as dynamic frameworks, so you'll need to manually copy the files over if there is an update in this integration (i.e. the mapping layer). But you'll still be using Optimizely via CocoaPods and not have to write the mapping code yourselves.

**Comment by f2prateek** [comment]
The version issue is fixed on the latest release https://github.com/segment-integrations/analytics-ios-integration-optimizely/blob/master/CHANGELOG.md#version-111-24th-october-2016
